name: Deploy Symfony Application

on:
  push:
    branches:
      - main # Déclenche le workflow sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérifier le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, intl, pdo, pdo_mysql, apcu
        ini-values: |
          memory_limit=2G
        tools: composer

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    # Étape 4 : Configuration des assets
    - name: Install Node.js and build assets
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: |
        npm install
        npm run build

    # Étape 5 : Vérification des migrations et mise à jour de la base de données
    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
